# http://docs.travis-ci.com/user/languages/c/
# start from https://github.com/rubinius/rubinius/blob/master/.travis.yml
language: c
sudo: required

compiler:
  - clang
  - gcc
os:
  - linux
# - osx
env:
  - DCNN=1
  - DCNN=0

matrix:
  exclude:
    - os: osx
      env: DCNN=1
    - os: osx
      compiler: gcc
#   allow_failures:
#     - compiler: clang

# get caffe from ppa
before_install:
  - if [ "$TRAVIS_OS_NAME" = linux ] && [ "$DCNN" = 1 ]; then sudo add-apt-repository ppa:lemonsqueeze/pachi -y ; fi
  - if [ "$TRAVIS_OS_NAME" = linux ] && [ "$DCNN" = 1 ]; then sudo apt-get update -q ; fi
  - if [ "$TRAVIS_OS_NAME" = linux ] && [ "$DCNN" = 1 ]; then sudo apt-get install -y libcaffe-cpu-dev pachi-go-data; fi
# XXX remove once pachi-data package is updated
  - if [ "$TRAVIS_OS_NAME" = linux ] && [ "$DCNN" = 1 ] && ! [ -f /usr/share/pachi-go/detlef54.prototxt ]; then sudo mv /usr/share/pachi-go/golast19.prototxt /usr/share/pachi-go/detlef54.prototxt; fi
  - if [ "$TRAVIS_OS_NAME" = linux ] && [ "$DCNN" = 1 ] && ! [ -f /usr/share/pachi-go/detlef54.trained ];  then sudo mv /usr/share/pachi-go/golast.trained    /usr/share/pachi-go/detlef54.trained; fi

# https://blog.lukaspradel.com/continuous-integration-for-cmake-projects-using-travis-ci/  
script:
  - make -j2 DCNN=$DCNN BOARD_TESTS=1 DATADIR=/usr/share/pachi-go
  - make test
